data_sources:
  pilelog:
    type: "multi_excel"
    required_columns:
      - "Pile Number"
      - "Date"
      - "Auger"
      - "Drill Depth"
      - "Rock Depth"
      - "SED/Beam"
      - "SED/Beam Length"
      - "Concrete Pump"
      - "Sleeve"
      - "Actual Rock"
      - "Calc Conc"
    table_name: "combined_pilelog_data"
    upload_mode: "overwrite"
    output_path: "data/processed/combined_pilelog_data.csv"

job_data:
  type: "excel"
  file_path: "data/raw/5 Jobs Data.xlsx"
  required_columns:
    - Address
    - City
    - Estimator
    - Estimator Email
    - First Received Date
    - Foreman
    - Foreman Email
    - Foreman Phone
    - Job Area
    - Job Description
    - Job Name
    - Job Number
    - Job Value
    - Main Contractor
    - Onsite Finish
    - Onsite Start
    - Suburb
    - Successful Date
    - Supervisor
    - Supervisor Email
    - Supervisor Phone
    - unique id
  table_name: "job_data"
  upload_mode: "overwrite"
  batch_size: 20

upload:
  batch_size: 500
  fill_na: true
